### ISSUE TITLE
Elixir icon

### ISSUE THREAD

**Issue by Tiesco789** [gilbarbara/logos#673] opened 2023-12-04 18:43 UTC
**Name with link**
Elixir: https://elixir-lang.org/

**Description**
Add elixir icon please

**Link to the vector file, preferably from an official source**
https://www.vectorlogo.zone/logos/elixir-lang/index.html

**Comment by gilbarbara** [comment] 2023-12-05 04:29
Duplicate of #562

**Closed by gilbarbara** 2023-12-05 04:29 UTC
Labels: request
